#!/bin/sh
# SPDX-FileCopyrightText: 2026 Giovanni MARIANO
#
# SPDX-License-Identifier: MPL-2.0

# AleaGit pre-commit hook
# Validates geometry files before allowing a commit.
# Install with: aleagit init --hook
#
# Exit code 0 = OK, 1 = validation failed (commit blocked)

exec aleagit validate --pre-commit
